FROM golang:1.14.4 as builder

WORKDIR /go/src/original-covid-app-japan-prefecture-backend

COPY go.mod go.sum ./
RUN go mod download

COPY ./  ./

ARG CGO_ENABLED=0
ARG GOOS=linux
ARG GOARCH=amd64
RUN go build \
  -o /go/bin/original-covid-app-japan-prefecture-backend \
  -ldflags '-s -w'


FROM scratch as runner

COPY --from=builder /go/bin/original-covid-app-japan-prefecture-backend /app/original-covid-app-japan-prefecture-backend
COPY --from=builder /go/src/original-covid-app-japan-prefecture-backend/config.ini /app/config.ini

ENTRYPOINT ["/app/original-covid-app-japan-prefecture-backend"]